workflows:
  ios-release:
    name: iOS Release
    working_directory: portal_investidor-main
    environment:
      flutter: stable
      xcode: latest
      vars:
        IPHONEOS_DEPLOYMENT_TARGET: 14.0
    scripts:
      - ls -la
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app